### ISSUE TITLE
USER STORY 1: set up basic express application

### ISSUE THREAD

**Issue by 4rchie-r** [SchoolOfCode/bc17-w4d2-project-almost-super-lazy#1]
```[tasklist]
### Tasks
- [x] Clone down backend repo
- [x] Forming a clear README.MD file
- [x] File should containt details on how to install and run application VIA node on the command line
- [x] Said application needs to be express API
- [x] When I make a GET request to “http://localhost:3000/”, Then I should get back a response with status code of 200 and text saying “Hello World!”
- [x] Then I should also see that the Node API has also logged the request in the terminal (console.log)
```

**Comment by 4rchie-r** [comment]
Completed the first User Story!
