### ISSUE TITLE
User Story 2: Add basic security standards using Helmet

### ISSUE THREAD

**Issue by 4rchie-r** [SchoolOfCode/bc17-w4d2-project-almost-super-lazy#2]
```[tasklist]
### Tasks
- [x] Set up nodemon
- [x] set up helmet npm package
- [ ] add helmet as a middleware configuration
- [x] allow requests
- [x] allow "inspect response headers"
- [ ] hide  “X-Powered-By: Express”
```
